<?php
return array(
    '_root_'  => 'index/index',  // The default route
    '_404_'   => 'error/404',    // The main 404 route
    '_500_'   => 'error/500',    // The main 500 route

    'totalbuycount' => 'index/totalCount',
    'checkInvitcode' => 'index/checkInvitcode',
    'captcha'=> 'index/captcha',

    'signin' => 'center/signin',
    'signup' => 'center/signup',
    'signout' => 'center/signout',
    'forgot' => 'center/getforgot',
    'forgotemail' => 'center/forgotemail',
    'findpwd' => 'center/findpassword',
    'newpwd' => 'center/newpassword',
    'sendok'=> 'center/sendok',
    'checkname'=> 'center/checkname',

    'invit/:id' => 'invit/invit',
    'invit' => 'invit/index',

    'emailok'=>'member/emailok',
    'u/checkemail' => 'member/checkemail',
    'u/(\d+)' => 'home/index/$1',
    'u/(\d+)/orders' => 'home/orders/$1',
    'u/(\d+)/orders/p/(\d+)' => 'home/orders/$1/$2',
    'u/(\d+)/wins' => 'home/wins/$1',
    'u/(\d+)/wins/p/(\d+)' => 'home/wins/$1/$2',
    'u/(\d+)/posts' => 'home/posts/$1',
    'u/(\d+)/posts/p/(\d+)' => 'home/posts/$1/$2',

    'u' => 'member/index',
    'u/getnickname' => 'member/getnickname' ,
    'u/checknickname' => 'member/checknickname' ,
    'u/nickname' => 'member/addnickname' ,
    'u/getavatar' => 'member/getavatar',
    'u/avatar' => 'member/avatar',
    'u/avatar/upload' => 'member/avatarUpload',
    'u/getprofile' => 'member/getprofile',
    'u/profile' => 'member/profile',
    'u/code' => 'member/code',
    'u/usecode' => 'member/usecode',
    'u/passwd' => 'member/changepassword',
    'u/passwd/forgot' => 'member/forgotpassword',
    'u/message' => 'member/sms/index',
    'u/message/p/(\d+)' => 'member/sms/index/$1',

    'u/address' => 'member/address/index',
    'u/address/(\d+)' => 'member/address/view/$1',
    'u/address/add' => 'member/address/add',
    'u/address/(\d+)/update' => 'member/address/edit/$1',
    'u/address/(\d+)/delete' => 'member/address/delete/$1',
    'u/address/(\d+)/default' => 'member/address/default/$1',
    'u/address/(\d+)/undefault' => 'member/address/undefault/$1',

    'u/posts' => 'member/posts/index',
    'u/noposts' => 'member/posts/noposts',
    'u/posts/p/(\d+)' => 'member/posts/index/$1',
    'u/noposts/p/(\d+)' => 'member/posts/noposts/$1',
    'u/posts/view/(\d+)' => 'member/posts/view',
    'u/posts/getadd/(\d+)' => 'member/posts/getadd/$1',
    'u/posts/upload' => 'member/posts/upload',
    'u/posts/add' => 'member/posts/add',
    'u/posts/getedit/(\d+)' => 'member/posts/getedit/$1',
    'u/posts/edit/(\d+)' => 'member/posts/edit/$1',
    'u/posts/delete/(\d+)' => 'member/posts/delete/$1',

    'u/invit' => 'member/invit/index',
    'u/invit/p/(\d+)' => 'member/invit/index/$1',
    'u/brokerage' => 'member/brokerage/index',
    'u/brokerage/p/(\d+)' => 'member/brokerage/index/$1',

    'u/orders' => 'member/orders/my',
    'u/orders/p/(\d+)' => 'member/orders/my/$1',
    'u/wins' => 'member/wins/index',
    'u/win/p/\d+' => 'member/wins/index/$1',
    'u/getrecharge' => 'member/getrecharge',
    'u/recharge' => 'member/recharge',
    'u/moneylog' => 'member/moneylog/rechargeIndex',
    'u/moneylog/p/(\d+)' => 'member/moneylog/rechargeIndex/$1',
    'u/moneylog/b/(\d+)' => 'member/moneylog/buyIndex/$1',
    'u/moneylog/b' => 'member/moneylog/buyIndex',
     
    'u/mobile/first' => 'member/mobile/first',
    'u/mobile/second/(\d+)' => 'member/mobile/second/$1',
    'u/mobile/getcode' => 'member/mobile/getcode',
    'u/mobile/check' => 'member/mobile/check',
/*
    'u/friends' => 'friends/my',
    'u/follow' => 'friends/follow',
    'u/unfollow' => 'friends/unfollow',
*/
    'm/search/:title/p/:page' => 'items/search',
    'm/search/:title' => 'items/search',
    'm/(\d+)' => 'items/view/$1',
    'm' => 'items/index',
    'm/p/:page' => 'items/index',
    'm/c/:cate_id/b/:brand_id/s/:sort/p/:page' => 'items/index',
    'm/c/:cate_id/b/:brand_id/s/:sort' => 'items/index',
    'm/s/:sort/p/:page' => 'items/index',
    'm/s/:sort' => 'items/index',
    'm/c/:cate_id/s/:sort/p/:page' => 'items/index',
    'm/c/:cate_id/s/:sort' => 'items/index',
    'm/c/:cate_id/b/:brand_id/p/:page' => 'items/index',
    'm/c/:cate_id/b/:brand_id' => 'items/index',
    'm/c/:cate_id/p/:page' => 'items/index',
    'm/c/:cate_id' => 'items/index',

    'p' => 'posts/index',
    'p/up/(\d+)' => 'posts/up/$1',
    'p/p/(\d+)' => 'posts/index/$1',
    'p/s/(\w+)?' => 'posts/sort/$1',
    'p/s/(\w+)/p/(\d+)' => 'posts/sort/$1/$2',
    'p/(\d+)' => 'posts/view/$1',
    'comment/(\d+)' => 'comment/index/$1',
    'comment/(\d+)/p/(\d+)' => 'comment/index/$1/$2',
    'comment/(\d+)/add' => 'member/comments/add/$1',

    'w' => 'wins/index',
    'w/p/(\d+)' => 'wins/index/$1',
    'w/(\d+)' => 'wins/view/$1',
    'w/result' => 'wins/result',

    'l' => 'orders/index',
    'l/p/(\d+)' => 'orders/index/$1',
    'l/joined' => 'orders/joined',
    'l/posts' => 'posts/posts',
    'l/phases' => 'items/phases',

    'h' => 'help/page',
    'h/(\w+)' => 'help/page/$1',

    'notice/p/:page' => 'notice/index',
    'notice/(\d+)' => 'notice/view/$1',
    'notice' => 'notice/index',

    'image/:size/:link' => 'image/index',
);
